title: Graph Builder 2
description: Program and library for building mathematical graphs and visualizing algorithms wrote with C++ and Qt
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
